apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8-addons
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/ketangit/sample-addons-k8
    targetRevision: HEAD
    path: addons
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
